services:
  nginx:
    container_name: nginx-container
    build: ./requirements/nginx
    networks:
      - di_caprio
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/html
    env_file: 
      - .env
    restart: always
  mariadb:
    container_name: mariadb-container
    build: ./requirements/mariadb
    networks:
      - di_caprio
    volumes:
       - db:/var/lib/mysql
    env_file:
      - .env
    restart: always
  wordpress:
    container_name: wordpress-container
    build: ./requirements/wordpress
    networks:
      - di_caprio
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/html
    env_file: 
      - .env
    restart: always

networks:
  di_caprio:
    driver: bridge

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/erivero-/data/mariadb
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/erivero-/data/wordpress