
# Especifica la imagen base
FROM  debian:bullseye

# # Establece el directorio de trabajo (no sé si lo necesito)
# WORKDIR /app #por ejemplo

# # por ejemplo para copiar archivos de configuración
# COPY 

# # RUN ejecuta comandos en la terminal
# RUN 

# # Copia el resto de los archivos de la aplicación
# COPY . .

# # Expone el puerto que la aplicación utilizará
# # creo que en el caso de mariadb no es necesario
# EXPOSE 3306

 # Comando para ejecutar la aplicación
 CMD ["sleep", "10000"]
# provisional obviamente
